### ISSUE TITLE
Label position if control is located top*

### ISSUE THREAD

**Issue by AbelVM** [nerik/leaflet-graphicscale#2]
To optimize labels location, at **.leaflet-control-graphicscale-inner .label** class, add "bottom:0px;" only if the control is located at bottom\* (css, line 12).

If control is located on top*, this should be added to avoid overlapping of other controls:

``` CSS
.leaflet-control-graphicscale {
  margin-bottom: 10px;
}
```
